
FROM python:3.9.16-slim

WORKDIR /usr/src/app

COPY . .

## ADD IP ENV variable

ENV SERVER_ADDRESS=0.0.0.0
ENV SERVER_PORT=8080

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD ["python3", "client.py"] 
