services:
  client1:
    image: "client"
  client2:
    image: "client"
  client3:
    image: "client"
  server: # You will need to build the server if you have not done so. Run "docker build -t server server_src"
    image: "server"
    ports:
      - 8080:8080