# Run this docker compose to simulate multiple clients. Add as many as you want by changing the number of replicas below.
# If you're running the clients and server locally (localhost), make sure you specify the IP adress as 0.0.0.0
# You will need to build the server if you have not done so. Run "docker build -t server server_src"

services:
  server: # You will need to build the server if you have not done so. Run "docker build -t server server_src"
    image: federated-server
    build:
      context: ./federated
      dockerfile: Dockerfile.server
    volumes:
      - ./federated:/usr/src/app
    ports:
      - 8080:8080
    restart: on-failure
    stop_signal: SIGINT
  client: # You can use the client from the solutions of exercise 2: "docker build -t client 'solutions/exercise 2/'"
    image: federated-client
    build:
      context: ./federated
      dockerfile: Dockerfile.client
    volumes:
      - ./federated:/usr/src/app
    environment:
      SERVER_ADDRESS: "server"
    deploy:
      replicas: 8
    stop_signal: SIGINT
  dashboard:
    image: federated-dashboard
    build:
      context: ./federated
      dockerfile: Dockerfile.dashboard
    volumes:
      - ./federated:/usr/src/app
    ports:
      - 8050:8050
    environment:
      DASHBOARD_PORT: 8050
    restart: on-failure
    stop_signal: SIGINT

  