services:
  client1:
    image: "client"
    # ports:
      # - 8080:8080
  client2:
    image: "client"
    # ports:
    #   - 8080:8080
  client3:
    image: "client"
    # ports:
    #   - 8080:8080
  server:
    image: "server"
    ports:
      - 8080:8080