
FROM python:3.9.16-slim

WORKDIR /usr/src/app

COPY . .

ENV SERVER_ADDRESS = 0.0.0.0

RUN pip install --no-cache-dir -r requirements.txt


## EXPOSE the right port
EXPOSE 

CMD ["python3", "client.py", "${SERVER_ADDRESS}"] 
