
FROM python:3.9.16-slim

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY helpers.py .
COPY cfg.py .
COPY client.py .

EXPOSE 8080

ENTRYPOINT ["python3", "client.py"] 
