FROM python:3.9.16-slim

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY cfg.py .
COPY helpers.py .
COPY dashboard.py .

EXPOSE 8050

ENTRYPOINT ["python3", "dashboard.py"] 