FROM python:3.9.16-slim

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY clustered_data.py .
COPY server.py .

EXPOSE 8080

CMD ["python3", "server.py"] 