FROM python:3.9.16-slim

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV DASHBOARD_PORT=8050

COPY dashboard_config.py .
COPY dashboard.py .

EXPOSE 8050

CMD ["python3", "dashboard.py"] 