
FROM python:3.9.16-slim

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY clustered_data.py .

## ADD IP ENV variable
ENV SERVER_ADDRESS=0.0.0.0
ENV SERVER_PORT=8080


COPY client.py .

EXPOSE 8080

CMD ["python3", "client.py"] 
